name: Exploring Variables and Secrets

on: push

env:
  CONTAINER_REGISTRY: docker.io
  CONTAINER_USERNAME: test
  DOCKER_USERNAME: chanchanhe
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

      - name: Docker Login
        run: echo docker login --username ${{ vars.DOCKER_USERNAME}} --password-stdin  ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: echo docker push ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ vars.CONTAINER_REGISTRY }}/${{ vars.CONTAINER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
