name: Exploring Variables and Secrets

on: workflow_dispatch

env:
  CONTAINER_REGISTRY: docker.io
  CONTAINER_USERNAME: chanchanhe
  IMAGE_NAME: github-actions-nginx
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Docker Login
        run: echo docker login --username ${{ env.DOCKER_USERNAME}} --password-stdin  ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
